### ISSUE TITLE
Not working with Liquibase 3.5.3

### ISSUE THREAD

**Issue by afanasev** [mattbertolini/liquibase-slf4j#6] opened 2016-11-02 21:18 UTC
Not working with Liquibase 3.5.3, although works fine with 3.4.2. I understand this is probably an issue on Liquibase side again, so just FYI...

**Comment by mattbertolini** [comment] 2016-11-03 01:49
Can you provide a bit more detail? I just tested it with version 3.5.3 and the logs were printing out just fine.

* How are you using Liquibase? Command line, Spring, Servlet Listener, Ant, Maven, etc?
* How do you deploy your application? Jar, War, Ear?
* Any special aspects to your application (OSGi, custom classloaders, etc.)?
* Has this been reported to Liquibase yet? If so, do you have a issue number/forum post?

Thanks!

**Comment by afanasev** [comment] 2016-11-03 09:39
Thank you for a quick response! The only excuse for not providing that info is that I submitted an issue late at night.

- I am using Liquibase from command line.
- Well, I deploy jar, but actually it's empty for now, since all existing migrations are provided separately.
- Nothing special, the case is as simple as possible.
- Not yet.

I'm using liquibase-slf4j 2.0.0, slf4j-api and slf4j-log4j12 1.7.21, log4j 1.2.17 configured via properties file. With Liquibase 3.4.2 everything works fine. As soon as I change Liquibase version to 3.5.3 (and that's the only change), it looks like default logger configuration is being used, with console output and default layout.

**Comment by mattbertolini** [comment] 2016-11-03 14:19
Is it possible to provide me the command line flags you are using to run Liquibase? It will help me reconstruct the problem.

**Comment by afanasev** [comment] 2016-11-03 14:36
Running in Windows environment for now. Here's the part of corresponding bat file:
`java -Dlog4j.configuration=file:conf/log4j.properties ^
     -jar lib/liquibase-core.jar ^
     --defaultsFile=conf/liquibase.properties ^
     --classpath=%CLASSPATH% ^
     --logLevel=debug ^
     update`

where CLASSPATH = lib\slf4j-log4j12.jar;lib\slf4j-api.jar;lib\postgresql.jar;lib\log4j.jar;lib\liquibase-slf4j.jar;lib\liquibase-core.jar;lib\dbmigrator.jar;
The last JAR is my application.

**Comment by mattbertolini** [comment] 2016-11-05 03:37
I set up a similar project to yours and was able to recreate the issue. It looks like it is a bug with Liquibase. My recommendation is to create a bug report on [their tracker](https://liquibase.jira.com/). The Liquibase `ServiceLocator` is not finding the jars on the classpath given using the `--classpath` flag. I will continue to poke at it when I have some time but I can confirm it is not an issue with this logger implementation.

**Comment by afanasev** [comment] 2016-11-07 13:53
Thank you, Matt! Here's an issue I created in Liquibase tracker:
https://liquibase.jira.com/browse/CORE-2936

**Comment by mattbertolini** [comment] 2016-11-07 15:35
Cool. Thanks for creating the issue on the tracker. I will track it over there and close this ticket out. We'll reopen this if there is any work to do on this side. Thanks again.

**Closed by mattbertolini** 2016-11-07 15:35 UTC
